/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package info5100.university.example.UI.Student;

import info5100.university.example.AccessControl.AuthenticationService;
import info5100.university.example.AccessControl.User;
import info5100.university.example.AccessControl.UserDirectory;
import info5100.university.example.CourseCatalog.Course;
import info5100.university.example.CourseSchedule.CourseLoad;
import info5100.university.example.CourseSchedule.CourseOffer;
import info5100.university.example.CourseSchedule.CourseSchedule;
import info5100.university.example.CourseSchedule.Seat;
import info5100.university.example.CourseSchedule.SeatAssignment;
import info5100.university.example.Department.Department;
import info5100.university.example.Finance.FinanceManager;
import info5100.university.example.Finance.TuitionAccount;
import info5100.university.example.Grading.GradeCalculator;
import info5100.university.example.Persona.Faculty.FacultyProfile;
import info5100.university.example.Persona.StudentProfile;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 * Student Work Area Panel
 * @author Student Module Developer Nikhil
 */
public class StudentWorkAreaPanel extends javax.swing.JPanel {
    
    private Department department;
    private UserDirectory userDirectory;
    private FinanceManager financeManager;
    private JPanel cardPanel;
    private AuthenticationService authService;
    private StudentProfile currentStudent;
    
    // Constants for MSIS Program
    private static final int REQUIRED_CREDIT_HOURS = 32;
    private static final int MAX_CREDITS_PER_SEMESTER = 8;
    private static final String CORE_COURSE = "INFO5100";
    private static final int CORE_COURSE_CREDITS = 4;

      
    /**
     * Creates new form StudentWorkAreaPanel
     */
    public StudentWorkAreaPanel(Department dept, UserDirectory userDir, 
                                FinanceManager finMgr, 
                                JPanel parentCardPanel,
                                AuthenticationService auth,
                                StudentProfile student) {
        
        this.department = dept;
        this.userDirectory = userDir;
        this.financeManager = finMgr;
        this.cardPanel = parentCardPanel;
        this.authService = auth;
        this.currentStudent = student;
        
        initComponents();
        
        setupTabs();
        loadStudentInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        studentTabs = new javax.swing.JTabbedPane();
        panelCourseRegistration = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbRegSemester = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cmbSearchType = new javax.swing.JComboBox<>();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnShowAll = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnEnroll = new javax.swing.JButton();
        btnDrop = new javax.swing.JButton();
        lblCreditWarning = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourses = new javax.swing.JTable();
        panelTranscript = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cmbTranscriptSemester = new javax.swing.JComboBox<>();
        btnExportTranscript = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblOverallGPA = new javax.swing.JLabel();
        lblTotalCredits = new javax.swing.JLabel();
        lblAcademicStanding = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTranscript = new javax.swing.JTable();
        panelGraduationAudit = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblGradStatus = new javax.swing.JLabel();
        lblCreditsCompleted = new javax.swing.JLabel();
        lblCreditsRemaining = new javax.swing.JLabel();
        lblCoreStatus = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        progressBar = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblGradRequirements = new javax.swing.JTable();
        panelFinancial = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        lblCurrentBalance = new javax.swing.JLabel();
        lblTotalPaid = new javax.swing.JLabel();
        lblPaymentStatus = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        btnPayTuition = new javax.swing.JButton();
        btnViewStatement = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblPaymentHistory = new javax.swing.JTable();
        panelAssignments = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cmbAssignmentCourse = new javax.swing.JComboBox<>();
        btnRefreshAssignments = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        btnSubmitAssignment = new javax.swing.JButton();
        btnViewGrades = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblAssignments = new javax.swing.JTable();
        panelProfile = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        btnEditProfile = new javax.swing.JButton();
        btnSaveProfile = new javax.swing.JButton();
        btnCancelEdit = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtStudentId = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtProgram = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtAdvisor = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());