/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package info5100.university.example.UI.Student;

import info5100.university.example.AccessControl.AuthenticationService;
import info5100.university.example.AccessControl.User;
import info5100.university.example.AccessControl.UserDirectory;
import info5100.university.example.CourseCatalog.Course;
import info5100.university.example.CourseSchedule.CourseLoad;
import info5100.university.example.CourseSchedule.CourseOffer;
import info5100.university.example.CourseSchedule.CourseSchedule;
import info5100.university.example.CourseSchedule.Seat;
import info5100.university.example.CourseSchedule.SeatAssignment;
import info5100.university.example.Department.Department;
import info5100.university.example.Finance.FinanceManager;
import info5100.university.example.Finance.TuitionAccount;
import info5100.university.example.Grading.GradeCalculator;
import info5100.university.example.Persona.Faculty.FacultyProfile;
import info5100.university.example.Persona.StudentProfile;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 * Student Work Area Panel
 * @author Student Module Developer Nikhil
 */
public class StudentWorkAreaPanel extends javax.swing.JPanel {
    
    private Department department;
    private UserDirectory userDirectory;
    private FinanceManager financeManager;
    private JPanel cardPanel;
    private AuthenticationService authService;
    private StudentProfile currentStudent;
    
    // Constants for MSIS Program
    private static final int REQUIRED_CREDIT_HOURS = 32;
    private static final int MAX_CREDITS_PER_SEMESTER = 8;
    private static final String CORE_COURSE = "INFO5100";
    private static final int CORE_COURSE_CREDITS = 4;

      
    /**
     * Creates new form StudentWorkAreaPanel
     */
    public StudentWorkAreaPanel(Department dept, UserDirectory userDir, 
                                FinanceManager finMgr, 
                                JPanel parentCardPanel,
                                AuthenticationService auth,
                                StudentProfile student) {
        
        this.department = dept;
        this.userDirectory = userDir;
        this.financeManager = finMgr;
        this.cardPanel = parentCardPanel;
        this.authService = auth;
        this.currentStudent = student;
        
        initComponents();
        
        setupTabs();
        loadStudentInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        studentTabs = new javax.swing.JTabbedPane();
        panelCourseRegistration = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbRegSemester = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cmbSearchType = new javax.swing.JComboBox<>();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnShowAll = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnEnroll = new javax.swing.JButton();
        btnDrop = new javax.swing.JButton();
        lblCreditWarning = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourses = new javax.swing.JTable();
        panelTranscript = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cmbTranscriptSemester = new javax.swing.JComboBox<>();
        btnExportTranscript = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblOverallGPA = new javax.swing.JLabel();
        lblTotalCredits = new javax.swing.JLabel();
        lblAcademicStanding = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTranscript = new javax.swing.JTable();
        panelGraduationAudit = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblGradStatus = new javax.swing.JLabel();
        lblCreditsCompleted = new javax.swing.JLabel();
        lblCreditsRemaining = new javax.swing.JLabel();
        lblCoreStatus = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        progressBar = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblGradRequirements = new javax.swing.JTable();
        panelFinancial = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        lblCurrentBalance = new javax.swing.JLabel();
        lblTotalPaid = new javax.swing.JLabel();
        lblPaymentStatus = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        btnPayTuition = new javax.swing.JButton();
        btnViewStatement = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblPaymentHistory = new javax.swing.JTable();
        panelAssignments = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cmbAssignmentCourse = new javax.swing.JComboBox<>();
        btnRefreshAssignments = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        btnSubmitAssignment = new javax.swing.JButton();
        btnViewGrades = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblAssignments = new javax.swing.JTable();
        panelProfile = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        btnEditProfile = new javax.swing.JButton();
        btnSaveProfile = new javax.swing.JButton();
        btnCancelEdit = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtStudentId = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtProgram = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtAdvisor = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());


                // Course Registration Tab
        panelCourseRegistration.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Semester:");
        jPanel1.add(jLabel1);

        cmbRegSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fall2024", "Spring2025", "Summer2025" }));
        jPanel1.add(cmbRegSemester);

        jLabel2.setText("Search by:");
        jPanel1.add(jLabel2);

        cmbSearchType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Course ID", "Course Name", "Instructor" }));
        jPanel1.add(cmbSearchType);

        txtSearch.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel1.add(txtSearch);

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearch);

        btnShowAll.setText("Show All");
        btnShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllActionPerformed(evt);
            }
        });
        jPanel1.add(btnShowAll);

        panelCourseRegistration.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        btnEnroll.setText("Enroll in Selected Course");
        btnEnroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrollActionPerformed(evt);
            }
        });
        jPanel2.add(btnEnroll);

        btnDrop.setText("Drop Selected Course");
        btnDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDropActionPerformed(evt);
            }
        });
        jPanel2.add(btnDrop);

        lblCreditWarning.setText("Current Credits: 0 / 8 max per semester");
        jPanel2.add(lblCreditWarning);

        panelCourseRegistration.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        tblCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Course ID", "Course Name", "Instructor", "Credits", "Schedule", "Seats Available", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCourses);

        panelCourseRegistration.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        studentTabs.addTab("Course Registration", panelCourseRegistration);

        // Transcript Tab
        panelTranscript.setLayout(new java.awt.BorderLayout());

        jLabel3.setText("View by Semester:");
        jPanel3.add(jLabel3);

        cmbTranscriptSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Semesters", "Fall2024", "Spring2025", "Summer2025" }));
        cmbTranscriptSemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTranscriptSemesterActionPerformed(evt);
            }
        });
        jPanel3.add(cmbTranscriptSemester);

        btnExportTranscript.setText("Export Transcript");
        btnExportTranscript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportTranscriptActionPerformed(evt);
            }
        });
        jPanel3.add(btnExportTranscript);

        panelTranscript.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setLayout(new java.awt.GridLayout(1, 3, 10, 0));

        lblOverallGPA.setText("Overall GPA: 0.00");
        lblOverallGPA.setFont(new java.awt.Font("Segoe UI", 1, 14));
        jPanel4.add(lblOverallGPA);

        lblTotalCredits.setText("Total Credits: 0");
        lblTotalCredits.setFont(new java.awt.Font("Segoe UI", 1, 14));
        jPanel4.add(lblTotalCredits);

        lblAcademicStanding.setText("Academic Standing: Good Standing");
        lblAcademicStanding.setFont(new java.awt.Font("Segoe UI", 1, 14));
        jPanel4.add(lblAcademicStanding);

        panelTranscript.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        tblTranscript.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Term", "Course ID", "Course Name", "Grade", "Credits", "Quality Points", "Term GPA", "Overall GPA", "Standing"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblTranscript);

        panelTranscript.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        studentTabs.addTab("Transcript", panelTranscript);

        // Graduation Audit Tab
        panelGraduationAudit.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.GridLayout(4, 1, 5, 5));

        lblGradStatus.setText("Graduation Status: NOT READY");
        lblGradStatus.setFont(new java.awt.Font("Segoe UI", 1, 16));
        jPanel5.add(lblGradStatus);

        lblCreditsCompleted.setText("Credits Completed: 0 / 32");
        jPanel5.add(lblCreditsCompleted);

        lblCreditsRemaining.setText("Credits Remaining: 32");
        jPanel5.add(lblCreditsRemaining);

        lblCoreStatus.setText("Core Course (INFO5100): Not Completed");
        jPanel5.add(lblCoreStatus);

        panelGraduationAudit.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel6.setLayout(new java.awt.BorderLayout());

        progressBar.setMaximum(32);
        progressBar.setStringPainted(true);
        jPanel6.add(progressBar, java.awt.BorderLayout.CENTER);

        jLabel4.setText("Progress to Graduation:");
        jPanel6.add(jLabel4, java.awt.BorderLayout.PAGE_START);

        panelGraduationAudit.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        tblGradRequirements.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Requirement", "Required", "Completed", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblGradRequirements);

        panelGraduationAudit.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        studentTabs.addTab("Graduation Audit", panelGraduationAudit);


               // Financial Tab
        panelFinancial.setLayout(new java.awt.BorderLayout());

        jPanel7.setLayout(new java.awt.GridLayout(3, 1, 5, 5));

        lblCurrentBalance.setText("Current Balance: $0.00");
        lblCurrentBalance.setFont(new java.awt.Font("Segoe UI", 1, 14));
        jPanel7.add(lblCurrentBalance);

        lblTotalPaid.setText("Total Paid: $0.00");
        lblTotalPaid.setFont(new java.awt.Font("Segoe UI", 1, 14));
        jPanel7.add(lblTotalPaid);

        lblPaymentStatus.setText("Payment Status: No Outstanding Balance");
        lblPaymentStatus.setFont(new java.awt.Font("Segoe UI", 1, 14));
        jPanel7.add(lblPaymentStatus);

        panelFinancial.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        btnPayTuition.setText("Pay Tuition");
        btnPayTuition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayTuitionActionPerformed(evt);
            }
        });
        jPanel8.add(btnPayTuition);

        btnViewStatement.setText("View Statement");
        btnViewStatement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewStatementActionPerformed(evt);
            }
        });
        jPanel8.add(btnViewStatement);

        panelFinancial.add(jPanel8, java.awt.BorderLayout.PAGE_END);

        tblPaymentHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Date", "Description", "Amount", "Type", "Balance After"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblPaymentHistory);

        panelFinancial.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        studentTabs.addTab("Financial", panelFinancial);
